---
    apiVersion: v1
    kind: Service
    metadata:
      name: alibabacloud-exporter
      labels:
        app: alibabacloud-exporter
    spec:
      ports:
      - port: 8081
        targetPort: 8081
      selector:
        app: alibabacloud-exporter
      sessionAffinity: None
      type: ClusterIP
    ---
    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: alibabacloud-exporter
    spec:
      replicas: 1
      minReadySeconds: 15
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
          maxSurge: 1
      template:
        metadata:
          labels:
            app: alibabacloud-exporter
        spec:
          containers:
          - name: alibabacloud-exporter
            image: siangyeh8818/alibabacloud-exporter:1.0
            imagePullPolicy: Always
            ports:
            - containerPort: 8081
              protocol: TCP
            env:
            - name: ACCESS_KEY_ID
              value: "YOur KEY ID"
            - name: ACCESS_KEY_SECRET
              value: "YOUR KEY SECRET"
            - name: REGION_ID
              value: "cn-shanghai"
            - name: Get_API_INTERNAL_TIME
              value: "180m"              
              #YOur REGION_ID
              #https://www.alibabacloud.com/help/zh/doc-detail/40654.htm
